[project]
name = "untitled-folder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.1",
    "uvicorn>=0.38.0",
]

[tool.uv.workspace]
members = [
    "DB",
    "DATABASE INTEGRATION",
]
